jobs:
  - pmc:
      - GL2C_HIT
  - pmc:
      - GL2C_MISS
  - pmc:
      - LDSBankConflict
  - pmc:
      - ALUStalledByLDS
  - pmc:
      - SQ_INSTS_VALU
  - pmc:
      - SQ_INSTS_LDS
  - pmc:
      - VALUUtilization
  - pmc:
      - SALUInsts
  - pmc:
      - MemUnitBusy
  - pmc:
      - MeanOccupancyPerCU
  - pmc:
      - WAVE_ISSUE_WAIT
  - pmc:
      - GRBM_GUI_ACTIVE
  - pmc:
      - TA_UTIL
  - pmc:
      - SPI_UTIL