jobs:
  - pmc:
      - LDSBankConflict
  - pmc:
      - ALUStalledByLDS
  - pmc:
      - GL2C_HIT
  - pmc:
      - GL2C_MISS
  - pmc:
      - SQ_INSTS_VALU
  - pmc:
      - SQ_INSTS_LDS
  - pmc:
      - VALUBusy
  - pmc:
      - SALUInsts
  - pmc:
      - MemUnitBusy
  - pmc:
      - WriteUnitStalled
  - pmc:
      - WAVE_ISSUE_WAIT
  - pmc:
      - WAVE_DEP_WAIT
  - pmc:
      - GPUBusy
  - pmc:
      - MeanOccupancyPerCU
  - pmc:
      - OccupancyPercent
  - pmc:
      - VALUUtilization
